### ISSUE TITLE
authorship on JOSS paper about drms

### ISSUE THREAD

**Issue by mbobra** [sunpy/drms#27]
:wave: @nabobalis @dpshelio @Cadair @nitinkgp23 

@kbg and I are writing a paper on drms for JOSS. Would you like to be an author? Please let us know!

**Comment by nabobalis** [comment]
i'm ok, all i've ever done is release this once.

**Comment by nitinkgp23** [comment]
Thanks, I would love to! Please let me know if I can contribute in any way.

**Comment by Cadair** [comment]
Yeah I am on board.

**Comment by kbg** [comment]
I just created PR #28 with the paper @mbobra and I came up. Feel free to add comments there and check if your name, affiliation, and ORCID are correct.

I plan to submit the paper on Monday, so please let me know if you want to have something changed.

**Comment by kbg** [comment]
I merged PR #28 to the feature branch `joss-paper` and submitted it to [JOSS](https://joss.theoj.org/papers/active). I hope we can keep the extra branch until the paper is accepted, because I don't want to pollute the master branch with more than one figure (which might need to be changed to PNG instead of PDF).

**Comment by dpshelio** [comment]
Thanks @mbobra, but I don't think I deserve it ;)

**Comment by kbg** [comment]
Ok. But as we said: Everybody is invited as an author. I plan to do the release for the JOSS paper tomorrow. So please let me know by tomorrow, if anybody changes their mind.

**Comment by kbg** [comment]
Thanks to everybody. The paper was accepted, so I'm closing this issue now.
